# Generated by Django 2.2.4 on 2019-11-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('cod_ciud', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('cod_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('cod_user', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('compañia', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('fec_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estado', models.CharField(max_length=1)),
                ('cod_ciud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='cod_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pais'),
        ),
    ]
