# Generated by Django 2.2.4 on 2019-11-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20191124_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_producto',
            fields=[
                ('cod_cat', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proveedor',
            fields=[
                ('cod_tipo_prov', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('X', 'Inactivo')], max_length=2),
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('cod_prov', models.IntegerField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=50)),
                ('ruc', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=30)),
                ('empresa', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('X', 'Inactivo')], max_length=2)),
                ('cod_ciud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ciudad')),
                ('cod_tipo_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tipo_proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('cod_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=90)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('X', 'Inactivo')], max_length=2)),
                ('cod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria_producto')),
                ('cod_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.proveedor')),
            ],
        ),
    ]
