# Generated by Django 2.2.4 on 2019-11-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20191124_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('cod_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('precio_total', models.IntegerField()),
                ('cod_prod', models.ManyToManyField(to='tienda.producto')),
                ('cod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
    ]
